config/routes.rb
Rails.application.routes.draw do
  
  resources :reserva_aceita
  resources :solicitacao_pontuals
  get 'solicitacao_pontuals/index'
  get 'welcome/index'
  # get 'sessions/new'
  # get 'users/new'
  get 'sobre_nos/index'
  get 'aaa/index'
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :reservas
  resources :atleticas
  resources :quadras
  # resources :aceita_reservas

  get 'aceitarReservas' => 'aceita_reservas#index'
  post 'aceitarReservas' => 'aceita_reservas#set_parametros'
  get '/aceitarReservas/:id' => 'aceita_reservas#show'
  get '/aprovar/:id' => 'aceita_reservas#new'
  post '/aprovar/:id' => 'aceita_reservas#create'
  
  # get '/aprovar/:id' => 'reserva_aceita#new'
  # post '/aprovar/:id' => 'reserva_aceita#create'
  get 'laausp/index'

  get 'tabela' => 'tabela#index'

  #post 'password/forgot' => 'password#forgot'
  #post 'password/reset'  => 'password#reset'
  #resources :password_reset
  #get 'password/forgot' => 'password#forgot'
  #get 'password/reset'  => 'password#reset'
  get 'resetQuadras' => 'aceita_reservas#reiniciarQuadra'
  get 'resetReservas' => 'reservas#reset'
  get 'criaLaausp' => 'users#criaLaausp'
  #get 'ver_reservas/index', as 'ver_reservas_index'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atletica.rb
class Atletica < ApplicationRecord
    has_secure_password 
end

app/models/quadra.rb
class Quadra < ApplicationRecord
    serialize :esportes
    serialize :seg
    serialize :ter
    serialize :qua
    serialize :qui
    serialize :sex
end

app/models/reserva.rb
class TimeValidator < ActiveModel::Validator
    def validate(record)
        if record.termino < record.inicio + 90*60
            record.errors.add(:termino, ": o horário de término deve ser pelo menos 1h30 após o início")
        end
    end
end

class Reserva < ApplicationRecord

    belongs_to :user
    # , class_name: "object", foreign_key: "object_id"
    include ActiveModel::Validations

    validates_presence_of :inicio,
    message: "Complete os campos vazios"
    validates_presence_of :termino,
    message: "Complete os campos vazios"

    validates_with TimeValidator
    
end

app/models/reserva_aceitum.rb
class ReservaAceitum < ApplicationRecord
end

app/models/solicitacao_pontual.rb
class SolicitacaoPontual < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reservas
    # , class_name: "object", foreign_key: "reference_id"
    has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    enum role: [:LAAUSP, :atletica]
    after_initialize :set_default_role, :if => :new_record?
    def set_default_role
        self.role ||= :atletica
    end

    #FORGOT PASSWORD
    def generate_password_token!
        self.reset_password_token = generate_token
        self.reset_password_sent_at = Time.now.utc
        save!
    end

    def password_token_valid?
        (self.reset_password_sent_at + 4.hours) > Time.now.utc
    end

    def reset_password!(password)
        self.reset_password_token = nil
        self.password = password
        save!
    end

    def send_password_reset
        generate_token(:password_reset_token)
        self.reset_password_sent_at = Time.zone.now
        save!
        UserMailer.password_reset(self).deliver
    end

    def generate_token(column)
        begin
            self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end

    #private

    #def generate_token
        #SecureRandom.hex(10)
    #end
    
    #END FORGOT PASSWORD
end

app/controllers/aaa_controller.rb
class AaaController < ApplicationController

  before_action :authorize

  def index
  end
end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]
  before_action :authorize
  # before_action :verfificar, only: [:new]

  # GET /reservas
  # GET /reservas.json
  def index
    if current_user.role != 'atletica'
      @reservas = Reserva.all
    else
      @reservas = Reserva.where(criador: current_user.name)
    end
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show
  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    @reserva = Reserva.new(reserva_params)
    @reserva.user_id = current_user.id
    @reserva.criador = current_user.name
    @reserva.status = 0
    respond_to do |format|
      if @reserva.save
        format.html { redirect_to @reserva, notice: 'Reserva atualizada com sucesso.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  def reset 
    Reserva.delete_all
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reservas resetadas com sucesso.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
      @criador = User.find(@reserva.user_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:modalidade, :naipe, :dia, :inicio, :termino, :odp, :ph)
    end

    
    # def verificaUsuario
    #   @user = current_user
    #   if @reserva.user_id == @user.id
    # rails generate model Quadra name:string ordem:integer atual:integer
    # rails g migration add_arrays_to_quadra esportes:string
    # 

end

app/helpers/aaa_helper.rb
module AaaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atleticas_helper.rb
module AtleticasHelper
end

app/helpers/inicial_page_helper.rb
module InicialPageHelper
end

app/helpers/laausp_helper.rb
module LaauspHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/quadras_helper.rb
module QuadrasHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in
        session[:user_id] = @user.id
    end
    def current_user
            @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_access
            if current_user.present?
                    redirect_to users_path
            end
    end
    def logged_in?
        !current_user.nil?
        end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/sobre_nos_helper.rb
module SobreNosHelper
end

app/helpers/tabela_helper.rb
module TabelaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/ver_reservas_helper.rb
module VerReservasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/reservas/_form.html.erb
<%= form_with(model: reserva, local: true) do |form| %>
  <% if reserva.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reserva.errors.count, "error") %> prohibited this reserva from being saved:</h2>

      <ul>
        <% reserva.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-3">

    <div class="form-group">
      <%= form.label :naipe %>
      <%= form.select :naipe, options_for_select(%w[Masculino Feminino Misto]), {}, {class: "form-control"} %>
    </div>
    
    <div class="form-group">
      <%= form.label :modalidade%>
      <%= form.select :modalidade, options_for_select(%w[Basquete Vôlei Handebol Futsal]), {}, {class: "form-control"} %>
    </div>

    <div class="field">
      <%= form.label :dia %>
      <%= form.select :dia, options_for_select(%w[Segunda Terça Quarta Quinta Sexta]), {}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :inicio %>
      <%= form.select :inicio, options_for_select(%w[17:00 17:30 18:00 18:30 19:00 19:30]), {}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :termino %>
      <%= form.select :termino, options_for_select(%w[18:30 19:00 19:30 20:00 20:30 21:00]), {}, {class: "form-control"} %>
    </div>

    <div class="form-group">
      <%= form.label :'PH' %>
      <%= form.select :ph, options_for_select(%w[1 2]), {}, {class: "form-control"}  %>
    </div>  
    
    <div class="form-group">
      <%= form.label :'ODP'%>
      <%= form.select :odp, options_for_select(%w[1 2 3]), {}, {class: "form-control"} %>
    </div>  

  </div>

  <div class="actions">
    <%= form.submit "Solicitar reserva", :class => 'botao'%>
  </div>

<% end %>

app/views/reservas/edit.html.erb
<h1>Editando Reserva</h1>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Ver', @reserva %> |
<%= link_to 'Voltar', reservas_path %>

app/views/reservas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table class = "tabela-reservas">
  <thead>
    <tr>
      <th>Criador</th>
      <th>Modalidade</th>
      <th>Naipe</th>
      <th>Dia</th>
      <th>Inicio</th>
      <th>Termino</th>
      <th>OdP</th>
      <th>PH</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservas.each do |reserva| %>
      <tr>
        <td><%= reserva.criador %></td>
        <td><%= reserva.modalidade %></td>
        <td><%= reserva.naipe %></td>
        <td><%= reserva.dia %></td>
        <td><%= reserva.inicio.time.strftime("%k:%M") %></td>
        <td><%= reserva.termino.time.strftime("%k:%M") %></td>
        <td><%= reserva.odp %></td>
        <td><%= reserva.ph %></td>
        <td><%= link_to 'Ver', reserva %></td>
        <td><%= link_to 'Editar', edit_reserva_path(reserva) %></td>
        <td><%= link_to 'Deletar', reserva, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.role == 'LAAUSP' %>
  <%= link_to 'Resetar Pedidos','/resetReservas', data: { confirm: 'Tem certeza que deseja resetar os pedidos/reservas?' } %>
<% end %>

<%= link_to 'Nova Reserva', new_reserva_path %>
<p> </p>
<%= link_to 'Voltar', aaa_index_path %>

app/views/reservas/new.html.erb
<h1>Nova Reserva</h1>

<div class = "texto">
<p class = 'fonte-texto'> Aqui você pode solicitar uma nova reserva </p>
<p class = 'fonte-texto'> <b> Naipe </b> - Escolha se você está solicitando uma reserva para uma modalidade masculina, feminina ou mista.<p>
<p class = 'fonte-texto'> <b> Modalidade </b> - Escolha para qual modalidade de quadra você deseja realizar uma reserva.</p>
<p class = 'fonte-texto'> <b> Dia </b> - Escolha para que dia da semana você deseja solicitar a reserva</p>
<p class = 'fonte-texto'> <b> Início </b> - Coloque um horário de início para a reserva </p>
<p class = 'fonte-texto'> <b> Término </b> - Coloque um horário de término para a reserva </p>
<p class = 'fonte-texto'> <b> PH (Prioridade de horário) </b> - Indique se prefere receber 1h de reserva de quadra no ínicio (1) ou no final (2) do treino </p>
<p class = 'fonte-texto'> <b> OdP (Ordem de Prioridade) </b> - Indique qual a prioridade desse treino dessa modalidade/naipe para receber reservas 
sendo 1 a maior prioridade e 3 a menor. Caso você esteja solicitando apenas um treino, coloque 1.</p>
</div>

<%= render 'form', reserva: @reserva %>

<%= link_to 'Voltar', reservas_path %>

app/views/reservas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Modalidade:</strong>
  <%= @reserva.modalidade %>
</p>


<p>
  <strong>Naipe:</strong>
  <%= @reserva.naipe %>
</p>


<p>
  <strong>Dia:</strong>
  <%= @reserva.dia %>
</p>


<p>
  <strong>Inicio:</strong>
  <%= @reserva.inicio.time.strftime("%k:%M") %>
</p>


<p>
  <strong>Termino:</strong>
  <%= @reserva.termino.time.strftime("%k:%M") %>
</p>

<p>
  <strong>Odp:</strong>
  <%= @reserva.odp %>
</p>

<p>
  <strong>Ph:</strong>
  <%= @reserva.ph %>
</p>

<p>
  <strong>Feita por:</strong>
  <%# <%= @reserva.user_id %> 
  <%= @reserva.criador %>
  
</p>

<%= link_to 'Editar', edit_reserva_path(@reserva) %> |
<%= link_to 'Voltar', reservas_path %>