config/routes.rb
Rails.application.routes.draw do
  
  resources :reserva_aceita
  resources :solicitacao_pontuals
  get 'solicitacao_pontuals/index'
  get 'welcome/index'
  # get 'sessions/new'
  # get 'users/new'
  get 'sobre_nos/index'
  get 'aaa/index'
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :reservas
  resources :atleticas
  resources :quadras
  # resources :aceita_reservas

  get 'aceitarReservas' => 'aceita_reservas#index'
  post 'aceitarReservas' => 'aceita_reservas#set_parametros'
  get '/aceitarReservas/:id' => 'aceita_reservas#show'
  get '/aprovar/:id' => 'aceita_reservas#new'
  post '/aprovar/:id' => 'aceita_reservas#create'
  
  # get '/aprovar/:id' => 'reserva_aceita#new'
  # post '/aprovar/:id' => 'reserva_aceita#create'
  get 'laausp/index'

  get 'tabela' => 'tabela#index'

  #post 'password/forgot' => 'password#forgot'
  #post 'password/reset'  => 'password#reset'
  #resources :password_reset
  #get 'password/forgot' => 'password#forgot'
  #get 'password/reset'  => 'password#reset'
  get 'resetQuadras' => 'aceita_reservas#reiniciarQuadra'
  get 'resetReservas' => 'reservas#reset'
  get 'criaLaausp' => 'users#criaLaausp'
  #get 'ver_reservas/index', as 'ver_reservas_index'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atletica.rb
class Atletica < ApplicationRecord
    has_secure_password 
end

app/models/quadra.rb
class Quadra < ApplicationRecord
    serialize :esportes
    serialize :seg
    serialize :ter
    serialize :qua
    serialize :qui
    serialize :sex
end

app/models/reserva.rb
class TimeValidator < ActiveModel::Validator
    def validate(record)
        if record.termino < record.inicio + 90*60
            record.errors.add(:termino, ": o horário de término deve ser pelo menos 1h30 após o início")
        end
    end
end

class Reserva < ApplicationRecord

    belongs_to :user
    # , class_name: "object", foreign_key: "object_id"
    include ActiveModel::Validations

    validates_presence_of :inicio,
    message: "Complete os campos vazios"
    validates_presence_of :termino,
    message: "Complete os campos vazios"

    validates_with TimeValidator
    
end

app/models/reserva_aceitum.rb
class ReservaAceitum < ApplicationRecord
end

app/models/solicitacao_pontual.rb
class SolicitacaoPontual < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reservas
    # , class_name: "object", foreign_key: "reference_id"
    has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    enum role: [:LAAUSP, :atletica]
    after_initialize :set_default_role, :if => :new_record?
    def set_default_role
        self.role ||= :atletica
    end

    #FORGOT PASSWORD
    def generate_password_token!
        self.reset_password_token = generate_token
        self.reset_password_sent_at = Time.now.utc
        save!
    end

    def password_token_valid?
        (self.reset_password_sent_at + 4.hours) > Time.now.utc
    end

    def reset_password!(password)
        self.reset_password_token = nil
        self.password = password
        save!
    end

    def send_password_reset
        generate_token(:password_reset_token)
        self.reset_password_sent_at = Time.zone.now
        save!
        UserMailer.password_reset(self).deliver
    end

    def generate_token(column)
        begin
            self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end

    #private

    #def generate_token
        #SecureRandom.hex(10)
    #end
    
    #END FORGOT PASSWORD
end

app/controllers/aaa_controller.rb
class AaaController < ApplicationController

  before_action :authorize

  def index
  end
end

app/controllers/solicitacao_pontuals_controller.rb
class SolicitacaoPontualsController < ApplicationController
  before_action :set_solicitacao_pontual, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /solicitacao_pontuals
  # GET /solicitacao_pontuals.json
  def index
    @solicitacao_pontuals = SolicitacaoPontual.all
  end

  # GET /solicitacao_pontuals/1
  # GET /solicitacao_pontuals/1.json
  def show
  end

  # GET /solicitacao_pontuals/new
  def new
    @solicitacao_pontual = SolicitacaoPontual.new
  end

  # GET /solicitacao_pontuals/1/edit
  def edit
  end

  # POST /solicitacao_pontuals
  # POST /solicitacao_pontuals.json
  def create
    @solicitacao_pontual = SolicitacaoPontual.new(solicitacao_pontual_params)
    UserMailer.reserva_pontual(@solicitacao_pontual).deliver_now

    respond_to do |format|
      if @solicitacao_pontual.save
        format.html { redirect_to @solicitacao_pontual, notice: 'Solicitacao pontual was successfully created.' }
        format.json { render :show, status: :created, location: @solicitacao_pontual }
      else
        format.html { render :new }
        format.json { render json: @solicitacao_pontual.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solicitacao_pontuals/1
  # PATCH/PUT /solicitacao_pontuals/1.json
  def update
    respond_to do |format|
      if @solicitacao_pontual.update(solicitacao_pontual_params)
        format.html { redirect_to @solicitacao_pontual, notice: 'Solicitacao pontual was successfully updated.' }
        format.json { render :show, status: :ok, location: @solicitacao_pontual }
      else
        format.html { render :edit }
        format.json { render json: @solicitacao_pontual.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicitacao_pontuals/1
  # DELETE /solicitacao_pontuals/1.json
  def destroy
    @solicitacao_pontual.destroy
    respond_to do |format|
      format.html { redirect_to solicitacao_pontuals_url, notice: 'Solicitacao pontual was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_solicitacao_pontual
      @solicitacao_pontual = SolicitacaoPontual.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def solicitacao_pontual_params
      params.require(:solicitacao_pontual).permit(:Solicitação)
    end
end

app/helpers/aaa_helper.rb
module AaaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atleticas_helper.rb
module AtleticasHelper
end

app/helpers/inicial_page_helper.rb
module InicialPageHelper
end

app/helpers/laausp_helper.rb
module LaauspHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/quadras_helper.rb
module QuadrasHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in
        session[:user_id] = @user.id
    end
    def current_user
            @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_access
            if current_user.present?
                    redirect_to users_path
            end
    end
    def logged_in?
        !current_user.nil?
        end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/sobre_nos_helper.rb
module SobreNosHelper
end

app/helpers/solicitacao_pontual_helper.rb
module SolicitacaoPontualHelper
end

app/helpers/solicitacao_pontuals_helper.rb
module SolicitacaoPontualsHelper
end

app/helpers/tabela_helper.rb
module TabelaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/solicitacao_pontuals/_form.html.erb
<%= form_with(model: solicitacao_pontual, local: true) do |form| %>
  <% if solicitacao_pontual.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(solicitacao_pontual.errors.count, "error") %> prohibited this solicitacao_pontual from being saved:</h2>

      <ul>
        <% solicitacao_pontual.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Solicitação %>
    <%= form.text_area :Solicitação, :class => 'caixa-texto' %>
  </div>

  <div class="actions">
    <%= form.submit "Enviar", :class => 'botao' %>
  </div>
<% end %>

app/views/solicitacao_pontuals/edit.html.erb
<h1>Editing Solicitacao Pontual</h1>

<%= render 'form', solicitacao_pontual: @solicitacao_pontual %>

<%= link_to 'Ver', @solicitacao_pontual %> |
<%= link_to 'Voltar', solicitacao_pontuals_path %>

app/views/solicitacao_pontuals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Solicitação Pontual</h1>

<table>
  <thead>
    <tr>
      <th>Solicitações</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solicitacao_pontuals.each do |solicitacao_pontual| %>
      <tr>
        <td><%= solicitacao_pontual.Solicitação %></td>
        <td><%= link_to 'Ver', solicitacao_pontual %></td>
        <td><%= link_to 'Editar', edit_solicitacao_pontual_path(solicitacao_pontual) %></td>
        <td><%= link_to 'Deletar', solicitacao_pontual, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Solicitação Pontual', new_solicitacao_pontual_path %>

app/views/solicitacao_pontuals/new.html.erb
<h1>Nova solicitãção Pontual</h1>

<p class = 'fonte-texto'>Descreva aqui sua solicitação, destacando: modalidade, naipe, quadra e horário desejado. Justifique a requisição (Ex: Quadra 10 livre entre 17h e 17h30)</p>

<%= render 'form', solicitacao_pontual: @solicitacao_pontual %>

<%= link_to 'Voltar', aaa_index_path %>

app/views/solicitacao_pontuals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Solicitação:</strong>
  <%= @solicitacao_pontual.Solicitação %>
</p>

<%= link_to 'Editar', edit_solicitacao_pontual_path(@solicitacao_pontual) %> |
<%= link_to 'Voltar', solicitacao_pontuals_path %>