config/routes.rb
Rails.application.routes.draw do
  
  resources :reserva_aceita
  resources :solicitacao_pontuals
  get 'solicitacao_pontuals/index'
  get 'welcome/index'
  # get 'sessions/new'
  # get 'users/new'
  get 'sobre_nos/index'
  get 'aaa/index'
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :reservas
  resources :atleticas
  resources :quadras
  # resources :aceita_reservas

  get 'aceitarReservas' => 'aceita_reservas#index'
  post 'aceitarReservas' => 'aceita_reservas#set_parametros'
  get '/aceitarReservas/:id' => 'aceita_reservas#show'
  get '/aprovar/:id' => 'aceita_reservas#new'
  post '/aprovar/:id' => 'aceita_reservas#create'
  
  # get '/aprovar/:id' => 'reserva_aceita#new'
  # post '/aprovar/:id' => 'reserva_aceita#create'
  get 'laausp/index'

  get 'tabela' => 'tabela#index'

  #post 'password/forgot' => 'password#forgot'
  #post 'password/reset'  => 'password#reset'
  #resources :password_reset
  #get 'password/forgot' => 'password#forgot'
  #get 'password/reset'  => 'password#reset'
  get 'resetQuadras' => 'aceita_reservas#reiniciarQuadra'
  get 'resetReservas' => 'reservas#reset'
  get 'criaLaausp' => 'users#criaLaausp'
  #get 'ver_reservas/index', as 'ver_reservas_index'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atletica.rb
class Atletica < ApplicationRecord
    has_secure_password 
end

app/models/quadra.rb
class Quadra < ApplicationRecord
    serialize :esportes
    serialize :seg
    serialize :ter
    serialize :qua
    serialize :qui
    serialize :sex
end

app/models/reserva.rb
class TimeValidator < ActiveModel::Validator
    def validate(record)
        if record.termino < record.inicio + 90*60
            record.errors.add(:termino, ": o horário de término deve ser pelo menos 1h30 após o início")
        end
    end
end

class Reserva < ApplicationRecord

    belongs_to :user
    # , class_name: "object", foreign_key: "object_id"
    include ActiveModel::Validations

    validates_presence_of :inicio,
    message: "Complete os campos vazios"
    validates_presence_of :termino,
    message: "Complete os campos vazios"

    validates_with TimeValidator
    
end

app/models/reserva_aceitum.rb
class ReservaAceitum < ApplicationRecord
end

app/models/solicitacao_pontual.rb
class SolicitacaoPontual < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reservas
    # , class_name: "object", foreign_key: "reference_id"
    has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    enum role: [:LAAUSP, :atletica]
    after_initialize :set_default_role, :if => :new_record?
    def set_default_role
        self.role ||= :atletica
    end

    #FORGOT PASSWORD
    def generate_password_token!
        self.reset_password_token = generate_token
        self.reset_password_sent_at = Time.now.utc
        save!
    end

    def password_token_valid?
        (self.reset_password_sent_at + 4.hours) > Time.now.utc
    end

    def reset_password!(password)
        self.reset_password_token = nil
        self.password = password
        save!
    end

    def send_password_reset
        generate_token(:password_reset_token)
        self.reset_password_sent_at = Time.zone.now
        save!
        UserMailer.password_reset(self).deliver
    end

    def generate_token(column)
        begin
            self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end

    #private

    #def generate_token
        #SecureRandom.hex(10)
    #end
    
    #END FORGOT PASSWORD
end

app/controllers/aaa_controller.rb
class AaaController < ApplicationController

  before_action :authorize

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :correct_user?, only: [:edit, :update, :destroy]
    before_action :authorize
    def new
        @user = User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            UserMailer.welcome_email(@user).deliver_now
            redirect_to @user, notice: "Usuário foi criado com sucesso!"
            #tire o método de comentário quando criar o helper.
            #Usuário depois de cadastrar-se acessa o sistema automaticamente
    #sign_in(@user)
        else 
            render action: :new
        end
    end
    def index
        @users = User.all
    end
    def show
        @user = User.find(params[:id])
    end
    def edit
        @user = User.find(params[:id]) 
    end
    
    def update
        @user = User.find(params[:id]) 
        if @user.update_attributes(user_params)
            redirect_to users_path
        else
            render action: :edit
        end
    end
    
    def destroy
        @user = User.find(params[:id]) 
        @user.destroy
        sign_out
        redirect_to root_path
    end

    def criaLaausp
        @user = User.new(name: "LAAUSP", email: "laausp@usp.br", password: "123456", role: :LAAUSP)
        if @user.save
            #UserMailer.welcome_email(@user).deliver_now
            redirect_to @user, notice: "Usuário foi criado com sucesso!"
            #tire o método de comentário quando criar o helper.
            #Usuário depois de cadastrar-se acessa o sistema automaticamente
    #sign_in(@user)
        else 
            render action: :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/aaa_helper.rb
module AaaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atleticas_helper.rb
module AtleticasHelper
end

app/helpers/inicial_page_helper.rb
module InicialPageHelper
end

app/helpers/laausp_helper.rb
module LaauspHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/quadras_helper.rb
module QuadrasHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in
        session[:user_id] = @user.id
    end
    def current_user
            @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_access
            if current_user.present?
                    redirect_to users_path
            end
    end
    def logged_in?
        !current_user.nil?
        end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/sobre_nos_helper.rb
module SobreNosHelper
end

app/helpers/tabela_helper.rb
module TabelaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/ver_reservas_helper.rb
module VerReservasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
            <% if @user.errors.any? %>
            <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <p><%= msg %></p>
                                   <% end %>
                        </ul>
            </div>
<% end %>
            <div class="field">
                        <%= f.label :Nome %>
                        <%= f.text_field :name, :class => 'caixa-texto' %>
            </div>
            <div class="field">
                        <%= f.label :email %>
                        <%= f.email_field :email, :class => 'caixa-texto' %>
            </div>
            <div class="field">
                        <%= f.label :senha %>
                        <%= f.password_field :password, :class => 'caixa-texto' %>
            </div>
            <div class="field">
                        <%= f.label :'Confirme sua Senha' %>
                        <%= f.password_field :password_confirmation, :class => 'caixa-texto' %>
            </div>
            <div class="actions">
                        <%= f.submit "Cadastrar", :class => 'botao'%>
            </div>
<% end %>
<ul>
            <p><%= link_to "Editar", edit_user_path(current_user) %></p>
            <p><%= link_to "Deletar", @user, method: :delete%></p>
</ul>

app/views/users/index.html.erb
<h1> Gerenciar Atléticas </h1>
<table class= 'tabela-users'>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user| %>
            <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= link_to "Visualizar", user %></td>
            </tr>
        <%end%>
    </tbody>
</table>

<p>Para cadastrar uma Atlética, <%= link_to "clique aqui!", new_user_path %></p>

app/views/users/show.html.erb
<html>
              <body>
                          <h3> Perfil de <%= @user.name %> </h3>

                          <p><b>Email:</b><%= @user.email %></p>
                          <p><b>Tipo de usuário:</b><%= @user.role %></p>
                          <% if current_user == @user %>
                                     <ul class = 'acoes-usuario'>
                                                 <p><%= link_to "Editar perfil", edit_user_path(current_user) %></p>
                                                 <p><%= link_to "Deletar perfil", @user, method: :delete%></p>
                                                 <% if current_user.role == "LAAUSP" %>
                                                 <p><%= link_to "Portal da LAAUSP", laausp_index_path%></p>
                                                 <% else%>
                                                 <p><%= link_to "Portal da Atlética", aaa_index_path%></p>
                                                 <%end%>
                                                 </ul>
                          <%end%>
              </body>
  </html>