config/routes.rb
Rails.application.routes.draw do
  
  resources :reserva_aceita
  resources :solicitacao_pontuals
  get 'solicitacao_pontuals/index'
  get 'welcome/index'
  # get 'sessions/new'
  # get 'users/new'
  get 'sobre_nos/index'
  get 'aaa/index'
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  resources :reservas
  resources :atleticas
  resources :quadras
  # resources :aceita_reservas

  get 'aceitarReservas' => 'aceita_reservas#index'
  post 'aceitarReservas' => 'aceita_reservas#set_parametros'
  get '/aceitarReservas/:id' => 'aceita_reservas#show'
  get '/aprovar/:id' => 'aceita_reservas#new'
  post '/aprovar/:id' => 'aceita_reservas#create'
  
  # get '/aprovar/:id' => 'reserva_aceita#new'
  # post '/aprovar/:id' => 'reserva_aceita#create'
  get 'laausp/index'

  get 'tabela' => 'tabela#index'

  #post 'password/forgot' => 'password#forgot'
  #post 'password/reset'  => 'password#reset'
  #resources :password_reset
  #get 'password/forgot' => 'password#forgot'
  #get 'password/reset'  => 'password#reset'
  get 'resetQuadras' => 'aceita_reservas#reiniciarQuadra'
  get 'resetReservas' => 'reservas#reset'
  get 'criaLaausp' => 'users#criaLaausp'
  #get 'ver_reservas/index', as 'ver_reservas_index'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atletica.rb
class Atletica < ApplicationRecord
    has_secure_password 
end

app/models/quadra.rb
class Quadra < ApplicationRecord
    serialize :esportes
    serialize :seg
    serialize :ter
    serialize :qua
    serialize :qui
    serialize :sex
end

app/models/reserva.rb
class TimeValidator < ActiveModel::Validator
    def validate(record)
        if record.termino < record.inicio + 90*60
            record.errors.add(:termino, ": o horário de término deve ser pelo menos 1h30 após o início")
        end
    end
end

class Reserva < ApplicationRecord

    belongs_to :user
    # , class_name: "object", foreign_key: "object_id"
    include ActiveModel::Validations

    validates_presence_of :inicio,
    message: "Complete os campos vazios"
    validates_presence_of :termino,
    message: "Complete os campos vazios"

    validates_with TimeValidator
    
end

app/models/reserva_aceitum.rb
class ReservaAceitum < ApplicationRecord
end

app/models/solicitacao_pontual.rb
class SolicitacaoPontual < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reservas
    # , class_name: "object", foreign_key: "reference_id"
    has_secure_password
    validates :name, presence: true, length: {maximum: 50}
    validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT= /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    enum role: [:LAAUSP, :atletica]
    after_initialize :set_default_role, :if => :new_record?
    def set_default_role
        self.role ||= :atletica
    end

    #FORGOT PASSWORD
    def generate_password_token!
        self.reset_password_token = generate_token
        self.reset_password_sent_at = Time.now.utc
        save!
    end

    def password_token_valid?
        (self.reset_password_sent_at + 4.hours) > Time.now.utc
    end

    def reset_password!(password)
        self.reset_password_token = nil
        self.password = password
        save!
    end

    def send_password_reset
        generate_token(:password_reset_token)
        self.reset_password_sent_at = Time.zone.now
        save!
        UserMailer.password_reset(self).deliver
    end

    def generate_token(column)
        begin
            self[column] = SecureRandom.urlsafe_base64
        end while User.exists?(column => self[column])
    end

    #private

    #def generate_token
        #SecureRandom.hex(10)
    #end
    
    #END FORGOT PASSWORD
end

app/controllers/aaa_controller.rb
class AaaController < ApplicationController

  before_action :authorize

  def index
  end
end

app/controllers/atleticas_controller.rb
class AtleticasController < ApplicationController
  before_action :set_atletica, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  # GET /atleticas
  # GET /atleticas.json
  def index
    @atleticas = Atletica.all
  end

  # GET /atleticas/1
  # GET /atleticas/1.json
  def show
  end

  # GET /atleticas/new
  def new
    @atletica = Atletica.new
  end

  # GET /atleticas/1/edit
  def edit
  end

  # POST /atleticas
  # POST /atleticas.json
  def create
    @atletica = Atletica.new(atletica_params)

    respond_to do |format|
      if @atletica.save
        format.html { redirect_to @atletica, notice: 'Atletica foi criada com sucesso' }
        format.json { render :show, status: :created, location: @atletica }
      else
        format.html { render :new }
        format.json { render json: @atletica.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atleticas/1
  # PATCH/PUT /atleticas/1.json
  def update
    respond_to do |format|
      if @atletica.update(atletica_params)
        format.html { redirect_to @atletica, notice: 'Atletica foi atualizada com sucesso' }
        format.json { render :show, status: :ok, location: @atletica }
      else
        format.html { render :edit }
        format.json { render json: @atletica.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atleticas/1
  # DELETE /atleticas/1.json
  def destroy
    @atletica.destroy
    respond_to do |format|
      format.html { redirect_to atleticas_url, notice: 'Atletica was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atletica
      @atletica = Atletica.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atletica_params
      params.require(:atletica).permit(:name, :email, :password)
    end
end

app/helpers/aaa_helper.rb
module AaaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atleticas_helper.rb
module AtleticasHelper
end

app/helpers/inicial_page_helper.rb
module InicialPageHelper
end

app/helpers/laausp_helper.rb
module LaauspHelper
end

app/helpers/password_helper.rb
module PasswordHelper
end

app/helpers/quadras_helper.rb
module QuadrasHelper
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in
        session[:user_id] = @user.id
    end
    def current_user
            @current_user ||= User.find_by(id: session[:user_id])
    end
    def block_access
            if current_user.present?
                    redirect_to users_path
            end
    end
    def logged_in?
        !current_user.nil?
        end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/sobre_nos_helper.rb
module SobreNosHelper
end

app/helpers/tabela_helper.rb
module TabelaHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/ver_reservas_helper.rb
module VerReservasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/atleticas/_form.html.erb
<% if @current_user.role == "atletica" %>

<%= form_with(model: atletica, local: true) do |form| %>
  <% if atletica.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(atletica.errors.count, "error") %> prohibited this atletica from being saved:</h2>

      <ul>
        <% atletica.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :name, :class => 'caixa-texto'  %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email,  :class => 'caixa-texto'  %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :password,  :class => 'caixa-texto'  %>
  </div>

  <div class="actions">
    <%= form.submit  "Cadastrar atlética",  :class => 'botao'  %>
  </div>
<% end %>

<% else %>
<p class = 'texto-atletica'> Você não tem permissão para acessar esta página</p>
<% end %>

app/views/atleticas/edit.html.erb
<% if @current_user.role == "atletica" %>

<h1>Editando Atletica</h1>

<%= render 'form', atletica: @atletica %>

<%= link_to 'Ver dados', @atletica %> |
<%= link_to 'Voltar', atleticas_path %>

<% else %>
<p class = 'texto-atletica'> Você não tem permissão para acessar esta página</p>
<% end %>

app/views/atleticas/index.html.erb
<% if @current_user.role == "atletica" %>

<p id="notice"><%= notice %></p>

<h1>Gerenciar Atléticas</h1>

<table class = "tabela-atleticas">
  <% @atleticas.each do |atletica| %>
    <tr>
      <td class = 'nome-atletica'><%= atletica.name %></td>
      <td><%= link_to 'Editar', edit_atletica_path(atletica)%></td>
      <td><%= link_to 'Excluir', atletica, method: :delete%></td>
    </tr>
  <% end %>
</table>

<br>
<div>
<%= link_to 'Cadastrar nova atlética', new_atletica_path %>
</div>

<% else %>
<p class = 'texto-atletica'> Você não tem permissão para acessar esta página</p>
<% end %>

app/views/atleticas/new.html.erb
<h1>Nova Atletica</h1>

<%= render 'form', atletica: @atletica %>

<%= link_to 'Voltar', atleticas_path %>

app/views/atleticas/show.html.erb
<% if @current_user.role == "atletica" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Atlética:</strong>
  <%= @atletica.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @atletica.email %>
</p>



<%= link_to 'Editar', edit_atletica_path(@atletica) %> |
<%= link_to 'Voltar', atleticas_path %>

<% else %>
<p class = 'texto-atletica'> Você não tem permissão para acessar esta página</p>
<% end %>